# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://github.com/uchan-nos/mikanos-build
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
    vb.cpus = 4
    vb.customize [
      "modifyvm"          , :id,
      "--vram"            , "256",
      "--clipboard"       , "bidirectional",
      "--accelerate3d"    , "on",
      "--hwvirtex"        , "on",
      "--nestedpaging"    , "on",
      "--largepages"      , "on",
      "--ioapic"          , "on",
      "--pae"             , "on",
      "--paravirtprovider", "kvm",
    ]
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    apt-get install apt-transport-https ca-certificates curl software-properties-common jq git ansible
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    apt-get update
  SHELL
end
